### ISSUE TITLE
about mosei raw data

### ISSUE THREAD

**Issue by LM-MSA** [pliang279/MultiViz#37]
The link to the original CMU-MOSEI dataset http://immortal.multicomp.cs.cmu.edu/raw_datasets/CMU_MOSEI.zip is no longer available, could you please share it?

**Comment by lvyiwei1** [comment]
Sorry for the inconvenience. Immortal servers are currently being moved so are temporarily unavailable. CMU-MOSEI can be downloaded here alternatively: https://github.com/matsuolab/CMU-MultimodalSDK/tree/master/mmsdk/mmdatasdk/dataset/standard_datasets/CMU_MOSEI
